apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - certificate.yml
  - ingress.yml
namePrefix: staging-
images:
  - name: homepage-staging
    newName: registry.aarnihalinen.fi/homepage
    newTag: staging
