apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      run: homepage
  template:
    metadata:
      labels:
        run: homepage
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: regcred-homepage
      containers:
        - name: homepage
          image: homepage-image
          ports:
            - containerPort: 80
      securityContext: {}
