apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: homepage
  labels:
    run: homepage
spec:
  type: ClusterIP
  selector:
    run: homepage
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
